name: Velox Unit Tests Suite

on:
  pull_request

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  velox-test:
    runs-on: self-hosted
    container: ubuntu:22.04
    steps:
      - uses: actions/checkout@v2
      - run: apt-get update
      - run: apt-get install -y cmake ccache build-essential ninja-build sudo
      - run: apt-get install -y maven
      - run: apt-get install -y libboost-all-dev libcurl4-openssl-dev
      - run: apt-get install -y libssl-dev flex libfl-dev git libprotobuf-dev
      - run: apt-get install -y libz-dev
      - name: Compile C++ unit tests
        run: |
          git submodule sync --recursive && git submodule update --init --recursive
          ./scripts/setup-ubuntu.sh 
          ./scripts/setup-adapters.sh 
          make debug EXTRA_CMAKE_FLAGS="-DVELOX_ENABLE_PARQUET=ON -DVELOX_BUILD_TESTING=ON -DVELOX_BUILD_TEST_UTILS=ON -DVELOX_ENABLE_ARROW=ON"
          cd _build/debug && ctest -j16 -VV -E "(velox_type_test|velox_dwio_common_test|velox_dwrf_e2e_filter_test|velox_parquet_e2e_filter_test|velox_windows_rank_test|velox_aggregates_test|velox_functions_test|velox_functions_spark_aggregates_test|velox_functions_spark_test|velox_hive_connector_test|velox_exec_test|velox_plan_conversion_test|velox_s3file_test|velox_hdfs_file_test|velox_windows_value_test)" --output-on-failure

  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: 'velox'
            exclude: 'external'
    steps:
      - uses: actions/checkout@v2
      - name: Run clang-format style check for C/C++ programs.
        uses: jidicula/clang-format-action@v3.5.1
        with:
          clang-format-version: '12'
          check-path: ${{ matrix.path['check'] }}
          exclude-regex: ${{ matrix.path['exclude'] }}
