name: Velox Unit Tests Suite

on:
  pull_request

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  velox-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get install -y cmake ccache build-essential
      - run: sudo apt-get install -y maven
      - run: sudo apt-get install -y libboost-all-dev libcurl4-openssl-dev
      - run: sudo apt-get install -y libssl-dev
      - run: sudo apt-get install -y libz-dev
      - name: Compile C++ unit tests
        run: |
          git submodule sync --recursive && git submodule update --init --recursive
          ./scripts/setup-ubuntu.sh 
          make release EXTRA_CMAKE_FLAGS="-DVELOX_ENABLE_ARROW=ON"

  gluten-test:
    runs-on: self-hosted
    steps:
      - name: Setup docker container
        run: |
          git clone https://github.com/oap-project/gluten && cd gluten
          BRANCH=$(echo ${GITHUB_REF#refs/heads/})
          sed -i 's/oap-project/"${GITHUB_REPOSITORY_OWNER}"/g' ep/build-velox/src/get_velox.sh
          sed -i 's/VELOX_BRANCH=main/VELOX_BRANCH="${BRANCH}"/g' ep/build-velox/src/get_velox.sh
          head -n10 ep/build-velox/src/get_velox.sh
          EXTRA_DOCKER_OPTIONS="--name velox-backend-ubuntu2004-test-$GITHUB_RUN_ID -e NUM_THREADS=30 --detach" \
          NON_INTERACTIVE=ON \
          MOUNT_MAVEN_CACHE=OFF \
          OS_IMAGE=ubuntu:20.04 \
          tools/gluten-te/ubuntu/cbash.sh sleep 14400
      - name: Setup maven cache
        run: |
          docker cp ~/.m2/repository velox-backend-ubuntu2004-test-$GITHUB_RUN_ID:/root/.m2/
      - name: Build Gluten Velox-backend third party
        run: |
          docker exec velox-backend-ubuntu2004-test-$GITHUB_RUN_ID bash -c '
          cd /opt/gluten/ep/build-arrow/src && \
          ./get_arrow.sh  && \
          ./build_arrow.sh --build_tests=ON --build_benchmarks=ON && \
          cd /opt/gluten/ep/build-velox/src && \
          ./get_velox.sh && \
          ./build_velox.sh'
      - name: Build Gluten CPP library
        run: |
          docker exec velox-backend-ubuntu2004-test-$GITHUB_RUN_ID bash -c '
          cd /opt/gluten/cpp && \
          mkdir build && cd build && cmake -DBUILD_TESTS=ON -DBUILD_BENCHMARKS=ON .. && make -j'
      - name: Build and run unit test for Spark 3.2.2
        run: |
          docker exec velox-backend-ubuntu2004-test-$GITHUB_RUN_ID bash -c '
          cd /opt/gluten && \
          mvn clean install -Pspark-3.2 -Pspark-ut -Pbackends-velox -DargLine="-Dspark.test.home=/opt/spark322"'
      - name: Run CPP unit test
        run: |
          docker exec velox-backend-ubuntu2004-test-$GITHUB_RUN_ID bash -c 'cd /opt/gluten/cpp/build && \
          ctest -V'
      # Cpp micro benchmarks will use generated files from unit test in backends-velox module.
      - name: Run micro benchmarks
        run: |
          docker exec velox-backend-ubuntu2004-test-$GITHUB_RUN_ID bash -c 'cd /opt/gluten/cpp/build/velox/benchmarks && \
          ./generic_benchmark --threads 1 --iterations 1'
      - name: TPC-H SF1.0 && TPC-DS SF0.1 Parquet local spark3.2
        run: |
          docker exec velox-backend-ubuntu2004-test-$GITHUB_RUN_ID bash -c 'cd /opt/gluten/tools/gluten-it && \
          mvn clean package -Pspark-3.2 \
          && java -Xmx5G -XX:ErrorFile=/var/log/java/hs_err_pid%p.log -cp target/gluten-it-1.0-SNAPSHOT-jar-with-dependencies.jar io.glutenproject.integration.tpc.Tpc \
            --backend-type=velox --benchmark-type=h --disable-aqe --off-heap-size=20g -s=1.0 --cpus=16 --iterations=1 \
          && java -Xmx5G -XX:ErrorFile=/var/log/java/hs_err_pid%p.log -cp target/gluten-it-1.0-SNAPSHOT-jar-with-dependencies.jar io.glutenproject.integration.tpc.Tpc \
            --backend-type=velox --benchmark-type=ds --off-heap-size=8g -s=0.1 --cpus=16 --iterations=1'
      - name: Build and Run unit test for Spark 3.3.1
        run: |
          docker exec velox-backend-ubuntu2004-test-$GITHUB_RUN_ID bash -c 'cd /opt/gluten && \
          mvn clean install -Pspark-3.3 -Pbackends-velox -Pspark-ut'
      - name: TPC-H SF1.0 && TPC-DS SF0.1 Parquet local spark3.3
        run: |
          docker exec velox-backend-ubuntu2004-test-$GITHUB_RUN_ID bash -c 'cd /opt/gluten/tools/gluten-it && \
          mvn clean package -Pspark-3.3 \
          && java -Xmx5G -XX:ErrorFile=/var/log/java/hs_err_pid%p.log -cp target/gluten-it-1.0-SNAPSHOT-jar-with-dependencies.jar io.glutenproject.integration.tpc.Tpc \
            --backend-type=velox --benchmark-type=h --disable-aqe --off-heap-size=20g -s=1.0 --cpus=16 --iterations=1 --skip-data-gen \
          && java -Xmx5G -XX:ErrorFile=/var/log/java/hs_err_pid%p.log -cp target/gluten-it-1.0-SNAPSHOT-jar-with-dependencies.jar io.glutenproject.integration.tpc.Tpc \
            --backend-type=velox --benchmark-type=ds --off-heap-size=8g -s=0.1 --cpus=16 --iterations=1 --skip-data-gen'
      - name: Run HBM CPP unit test
        run: |
          docker exec velox-backend-ubuntu2004-test-$GITHUB_RUN_ID bash -c 'cd /opt/gluten/cpp/build && \
          cmake -DBUILD_TESTS=ON -DENABLE_HBM=ON .. && \
          cmake --build . --target hbw_allocator_test -- -j && \
          ctest -V -R TestHbw'
      - name: Exit docker container
        if: ${{ always() }}
        run: |
          docker stop velox-backend-ubuntu2004-test-$GITHUB_RUN_ID || true
